apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  namespace: default
  labels:
    app: mywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec: 
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp:latest
        ports:
        - containerPort: 8181
        envFrom:
        - configMapRef:
            name: mywebapp-configmapv1.0
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"  
          limits:
            memory: "128Mi"
            cpu: "100m"
