# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: mywebapp-chart
namespace:
  # This sets the namespace for the deployment more information can be found here: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
  name: default

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: nginx
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

env:
  # This sets the environment variables for the deployment more information can be found here: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
  BG_COLOR: "'#12181b'"
  FONT_COLOR: "'#FFFFFF'"
  CUSTOM_HEADER: "My Custom Header"

  
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8181

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
