apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-ns

resources:
- ../../base
- ./namespace.yaml

patches:
- path: replicas.yaml
  target:
    kind: Deployment

namePrefix: dev-

configMapGenerator:
- name: mykustom-map
  envs:
  - config.properties
  behavior: replace 
