apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-argo 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml 
    path: helm-chart/webapp
    repoURL: https://github.com/victorbecerragit/mykustomapp.git
    targetRevision: HEAD
