apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-argo 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: webapp-argo
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: webapp-argo
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v1.0.0
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml 
    path: helm-chart/webapp
    repoURL: https://github.com/victorbecerragit/mykustomapp.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true